[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "Greetings"
version = "0.1.0"
dependencies = ["numpy"]

[tool.hatch.build.targets.wheel]
packages = [
  "src/sagittal_brain",
]